// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_command.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace XkProtobufData {

  /// <summary>Holder for reflection information generated from proto_command.proto</summary>
  public static partial class ProtoCommandReflection {

    #region Descriptor
    /// <summary>File descriptor for proto_command.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoCommandReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNwcm90b19jb21tYW5kLnByb3RvEhB4a19wcm90b2J1Zl9kYXRhKtoBCgxQ",
            "cm90b0NvbW1hbmQSDgoKUFJPVE9fTk9ORRAAEg8KClBST1RPX0NIQVQQzAgS",
            "GgoVUFJPVE9fUkVHSVNURVJBQ0NPVU5UEM0IEhAKC1BST1RPX0xPR0lOEM4I",
            "EhcKElBST1RPX1NFTEVDVFNFUlZFUhDPCBIVChBQUk9UT19DUkVBVEVST0xF",
            "ENAIEhUKEFBST1RPX1NFTEVDVFJPTEUQ0QgSGAoTUFJPVE9fUFVTSF9DSEFU",
            "SU5GTxCJJxIaChVQUk9UT19QVVNIX1BMQVlFUklORk8QiidiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::XkProtobufData.ProtoCommand), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ProtoCommand {
    [pbr::OriginalName("PROTO_NONE")] ProtoNone = 0,
    [pbr::OriginalName("PROTO_CHAT")] ProtoChat = 1100,
    [pbr::OriginalName("PROTO_REGISTERACCOUNT")] ProtoRegisteraccount = 1101,
    [pbr::OriginalName("PROTO_LOGIN")] ProtoLogin = 1102,
    [pbr::OriginalName("PROTO_SELECTSERVER")] ProtoSelectserver = 1103,
    [pbr::OriginalName("PROTO_CREATEROLE")] ProtoCreaterole = 1104,
    [pbr::OriginalName("PROTO_SELECTROLE")] ProtoSelectrole = 1105,
    [pbr::OriginalName("PROTO_PUSH_CHATINFO")] ProtoPushChatinfo = 5001,
    [pbr::OriginalName("PROTO_PUSH_PLAYERINFO")] ProtoPushPlayerinfo = 5002,
  }

  #endregion

}

#endregion Designer generated code
