//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Proto/proto_command.proto
namespace game.protobuf.data
{
    [global::ProtoBuf.ProtoContract(Name=@"ProtoCommand")]
    public enum ProtoCommand
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Chat", Value=1100)]
      Chat = 1100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RegisterAccount", Value=1101)]
      RegisterAccount = 1101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Login", Value=1102)]
      Login = 1102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SelectServer", Value=1103)]
      SelectServer = 1103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterGame", Value=1104)]
      EnterGame = 1104
    }
  
}