//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto_command.proto
namespace game.protobuf.data
{
    [global::ProtoBuf.ProtoContract(Name=@"ProtoCommand")]
    public enum ProtoCommand
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROTO_CHAT", Value=1100)]
      PROTO_CHAT = 1100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROTO_REGISTERACCOUNT", Value=1101)]
      PROTO_REGISTERACCOUNT = 1101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROTO_LOGIN", Value=1102)]
      PROTO_LOGIN = 1102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROTO_SELECTSERVER", Value=1103)]
      PROTO_SELECTSERVER = 1103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROTO_CREATEROLE", Value=1104)]
      PROTO_CREATEROLE = 1104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROTO_SELECTROLE", Value=1105)]
      PROTO_SELECTROLE = 1105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROTO_PUSH_CHATINFO", Value=5001)]
      PROTO_PUSH_CHATINFO = 5001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROTO_PUSH_PLAYERINFO", Value=5002)]
      PROTO_PUSH_PLAYERINFO = 5002
    }
  
}