//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Proto/proto_message_two.proto
// Note: requires additional types generated from: Proto/proto_struct.proto
namespace game.protobuf.data
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientSendData")]
  public partial class ClientSendData : global::ProtoBuf.IExtensible
  {
    public ClientSendData() {}
    
    private string _SenderName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SenderName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SenderName
    {
      get { return _SenderName; }
      set { _SenderName = value; }
    }
    private string _TalkMsg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"TalkMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TalkMsg
    {
      get { return _TalkMsg; }
      set { _TalkMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerSendData")]
  public partial class ServerSendData : global::ProtoBuf.IExtensible
  {
    public ServerSendData() {}
    
    private string _Result = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private string _NickName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"NickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string NickName
    {
      get { return _NickName; }
      set { _NickName = value; }
    }
    private string _TalkMsg = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"TalkMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TalkMsg
    {
      get { return _TalkMsg; }
      set { _TalkMsg = value; }
    }
    private string _TalkTime = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"TalkTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TalkTime
    {
      get { return _TalkTime; }
      set { _TalkTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"csRegisterAccount")]
  public partial class csRegisterAccount : global::ProtoBuf.IExtensible
  {
    public csRegisterAccount() {}
    
    private string _accountName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accountName
    {
      get { return _accountName; }
      set { _accountName = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _repeatPassword = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"repeatPassword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string repeatPassword
    {
      get { return _repeatPassword; }
      set { _repeatPassword = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scRegisterAccount")]
  public partial class scRegisterAccount : global::ProtoBuf.IExtensible
  {
    public scRegisterAccount() {}
    
    private bool _result = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"csLoginGame")]
  public partial class csLoginGame : global::ProtoBuf.IExtensible
  {
    public csLoginGame() {}
    
    private string _accountName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accountName
    {
      get { return _accountName; }
      set { _accountName = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scLoginGame")]
  public partial class scLoginGame : global::ProtoBuf.IExtensible
  {
    public scLoginGame() {}
    
    private bool _result = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"csServerList")]
  public partial class csServerList : global::ProtoBuf.IExtensible
  {
    public csServerList() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scServerList")]
  public partial class scServerList : global::ProtoBuf.IExtensible
  {
    public scServerList() {}
    
    private readonly global::System.Collections.Generic.List<struct_serverList> _ServerList = new global::System.Collections.Generic.List<struct_serverList>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ServerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<struct_serverList> ServerList
    {
      get { return _ServerList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"csEnterGame")]
  public partial class csEnterGame : global::ProtoBuf.IExtensible
  {
    public csEnterGame() {}
    
    private int _ServerId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scEnterGame")]
  public partial class scEnterGame : global::ProtoBuf.IExtensible
  {
    public scEnterGame() {}
    
    private int _ServerId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}