//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Proto/proto_struct.proto
namespace game.protobuf.data
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"struct_serverList")]
  public partial class struct_serverList : global::ProtoBuf.IExtensible
  {
    public struct_serverList() {}
    
    private string _serverName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"serverName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string serverName
    {
      get { return _serverName; }
      set { _serverName = value; }
    }
    private int _serverId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"serverId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int serverId
    {
      get { return _serverId; }
      set { _serverId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}